Ugly bug update with things that changed over the last 2-3 years.

diff --git a/bin/srcless b/bin/srcless
--- a/bin/srcless
+++ b/bin/srcless
@@ -1,3 +1,12 @@
-#!/usr/bin/fish
+#!/usr/bin/env bash
 
-pygmentize $argv | less -r -J -N -M
+set -o errexit
+set -o nounset
+set -o pipefail
+
+if [[ "$#" -lt 1 ]]; then
+  echo "Missing filename (\"$(basename "$0") --help\" for help)" >&2
+  exit 1
+fi
+
+pygmentize "$@" | less -r -J -N -M
